services:
  proxy:
    build:
      context: ./proxy
    ports:
      - "127.0.0.1:8081:8081" # mitmweb UI
    networks:
      public:
      internal_only:
        aliases:
          - proxy.local
networks:
  internal_only:
    internal: true
  public:
    driver: bridge
